# Generated by Django 5.1.2 on 2024-11-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_somethingelse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomethingElse',
        ),
    ]
